
name: Update index.html in GH Pages and generate global sitemap

on:
  workflow_dispatch:
  workflow_call:

jobs:
  update-gh-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Replace 'version/stable' with 'version/dev' in index.html
      run: |
        # Replace landing page with the dev version
        cp version/dev/index.html index.html
        sed -i 's/href="\([^:"]*\)"/href="version\/dev\/\1"/g' index.html
        sed -i 's/src="\([^:"]*\)"/src="version\/dev\/\1"/g' index.html
        # Replace "version/stable" with "version/dev" in the sitemap.xml
        sed -i 's/version\/stable/version\/dev/g' sitemap.xml

    - name: "Commit changes"
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "update index.html"

  run-global-sitemap-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: pip install -r ./requirements/requirements_doc.txt

    - name: Run script
      working-directory: ./.github/sripts
      run: python catsitemap.py

    - name: Upload sitemap index file
      uses: actions/upload-artifact@v4
      with:
        name: global-sitemap-file
        path: scripts/globalsitemap.xml